/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Countries;
import io.swagger.model.Country;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-05-27T22:30:01.988Z")

@Validated
@Api(value = "country", description = "the country API")
@RequestMapping(value = "")
public interface CountryApi {

    @ApiOperation(value = "", nickname = "deleteCountry", notes = "", response = Country.class, tags={ "country", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "No content", response = Country.class) })
    @RequestMapping(value = "/country/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Country> deleteCountry(@ApiParam(value = "",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "getCountries", notes = "", response = Countries.class, tags={ "country", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = Countries.class) })
    @RequestMapping(value = "/country",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Countries> getCountries();


    @ApiOperation(value = "", nickname = "getCountry", notes = "", response = Country.class, tags={ "country", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = Country.class) })
    @RequestMapping(value = "/country/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Country> getCountry(@ApiParam(value = "",required=true) @PathVariable("id") Integer id);


    @ApiOperation(value = "", nickname = "postCountry", notes = "", response = Country.class, tags={ "country", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Success", response = Country.class) })
    @RequestMapping(value = "/country",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Country> postCountry(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Country body);


    @ApiOperation(value = "", nickname = "updateCountry", notes = "", response = Country.class, tags={ "country", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = Country.class) })
    @RequestMapping(value = "/country/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Country> updateCountry(@ApiParam(value = "",required=true) @PathVariable("id") String id,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Country body);

}
