/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Weather;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-05-27T22:30:01.988Z")

@Validated
@Api(value = "weather", description = "the weather API")
@RequestMapping(value = "")
public interface WeatherApi {

    @ApiOperation(value = "", nickname = "getWeather", notes = "", response = Weather.class, tags={ "weather", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = Weather.class) })
    @RequestMapping(value = "/weather/{city_name}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Weather> getWeather(@ApiParam(value = "",required=true) @PathVariable("city_name") String city_name);

}
