/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Weather;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-05-27T22:30:01.988Z")

@Validated
@Api(value = "weather", description = "the weather API")
@RequestMapping(value = "")
public interface WeatherApi {

    @ApiOperation(value = "", nickname = "getWeather", notes = "", response = Weather.class, tags={ "weather", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = Weather.class) })
    @RequestMapping(value = "/weather/{city_name}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<String> getWeather(@ApiParam(value = "",required=true) @PathVariable("city_name") String city_name);

    @ApiOperation(value = "", nickname = "exportWeather", notes = "", response = String.class, tags={ "weather", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Success", response = String.class) })
    @RequestMapping(value = "/weather/export",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<String> exportWeather();

    @ApiOperation(value = "", nickname = "importWeather", notes = "", response = String.class, tags={ "weather", })
    @ApiResponses(value = {
            @ApiResponse(code = 201, message = "Success", response = String.class) })
    @RequestMapping(value = "/weather/import/{city_name}",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST)
    ResponseEntity<String> importWeather(@ApiParam(value = "",required=true) @PathVariable("city_name") String city_name, @ApiParam(value = "" ,required=true )  @Valid @RequestBody String csv);
}
