INSERT INTO Country VALUES
('AF', 'AFG', 'Afghánistán'),
('AX', 'ALA', 'Alandy'),
('AL', 'ALB', 'Albánie'),
('DZ', 'DZA', 'Alžírsko'),
('AS', 'ASM', 'Americká Samoa'),
('VI', 'VIR', 'Americké Panenské ostrovy'),
('AD', 'AND', 'Andorra'),
('AO', 'AGO', 'Angola'),
('AI', 'AIA', 'Anguilla'),
('AQ', 'ATA', 'Antarktida'),
('AG', 'ATG', 'Antigua a Barbuda'),
('AR', 'ARG', 'Argentina'),
('AM', 'ARM', 'Arménie'),
('AW', 'ABW', 'Aruba'),
('AU', 'AUS', 'Austrálie'),
('AZ', 'AZE', 'Ázerbájdžán'),
('BS', 'BHS', 'Bahamy'),
('BH', 'BHR', 'Bahrajn'),
('BD', 'BGD', 'Bangladéš'),
('BB', 'BRB', 'Barbados'),
('BE', 'BEL', 'Belgie'),
('BZ', 'BLZ', 'Belize'),
('BY', 'BLR', 'Bìlorusko'),
('BJ', 'BEN', 'Benin'),
('BM', 'BMU', 'Bermudy'),
('BT', 'BTN', 'Bhútán'),
('BO', 'BOL', 'Bolívie'),
('BQ', 'BES', 'Bonaire, Svatý Eustach a Saba'),
('BA', 'BIH', 'Bosna a Hercegovina'),
('BW', 'BWA', 'Botswana'),
('BV', 'BVT', 'Bouvetùv ostrov'),
('BR', 'BRA', 'Brazílie'),
('IO', 'IOT', 'Britské indickooceánské území'),
('VG', 'VGB', 'Britské Panenské ostrovy'),
('BN', 'BRN', 'Brunej'),
('BG', 'BGR', 'Bulharsko'),
('BF', 'BFA', 'Burkina Faso'),
('BI', 'BDI', 'Burundi'),
('CK', 'COK', 'Cookovy ostrovy'),
('CW', 'CUW', 'Curaçao'),
('TD', 'TCD', 'Èad'),
('ME', 'MNE', 'Èerná Hora'),
('CZ', 'CZE', 'Èesko'),
('CN', 'CHN', 'Èína'),
('DK', 'DNK', 'Dánsko'),
('DM', 'DMA', 'Dominika'),
('DO', 'DOM', 'Dominikánská republika'),
('DJ', 'DJI', 'Džibutsko'),
('EG', 'EGY', 'Egypt'),
('EC', 'ECU', 'Ekvádor'),
('ER', 'ERI', 'Eritrea'),
('EE', 'EST', 'Estonsko'),
('ET', 'ETH', 'Etiopie'),
('FO', 'FRO', 'Faerské ostrovy'),
('FK', 'FLK', 'Falklandy (Malvíny)'),
('FJ', 'FJI', 'Fidži'),
('PH', 'PHL', 'Filipíny'),
('FI', 'FIN', 'Finsko'),
('FR', 'FRA', 'Francie'),
('GF', 'GUF', 'Francouzská Guyana'),
('TF', 'ATF', 'Francouzská jižní a antarktická území'),
('PF', 'PYF', 'Francouzská Polynésie'),
('GA', 'GAB', 'Gabon'),
('GM', 'GMB', 'Gambie'),
('GH', 'GHA', 'Ghana'),
('GI', 'GIB', 'Gibraltar'),
('GD', 'GRD', 'Grenada'),
('GL', 'GRL', 'Grónsko'),
('GE', 'GEO', 'Gruzie'),
('GP', 'GLP', 'Guadeloupe'),
('GU', 'GUM', 'Guam'),
('GT', 'GTM', 'Guatemala'),
('GN', 'GIN', 'Guinea'),
('GW', 'GNB', 'Guinea-Bissau'),
('GG', 'GGY', 'Guernsey'),
('GY', 'GUY', 'Guyana'),
('HT', 'HTI', 'Haiti'),
('HM', 'HMD', 'Heardùv ostrov a McDonaldovy ostrovy'),
('HN', 'HND', 'Honduras'),
('HK', 'HKG', 'Hongkong'),
('CL', 'CHL', 'Chile'),
('HR', 'HRV', 'Chorvatsko'),
('IN', 'IND', 'Indie'),
('ID', 'IDN', 'Indonésie'),
('IQ', 'IRQ', 'Irák'),
('IR', 'IRN', 'Írán'),
('IE', 'IRL', 'Irsko'),
('IS', 'ISL', 'Island'),
('IT', 'ITA', 'Itálie'),
('IL', 'ISR', 'Izrael'),
('JM', 'JAM', 'Jamajka'),
('JP', 'JPN', 'Japonsko'),
('YE', 'YEM', 'Jemen'),
('JE', 'JEY', 'Jersey'),
('ZA', 'ZAF', 'Jihoafrická republika'),
('GS', 'SGS', 'Jižní Georgie a Jižní Sandwichovy ostrovy'),
('KR', 'KOR', 'Jižní Korea'),
('SS', 'SSD', 'Jižní Súdán'),
('JO', 'JOR', 'Jordánsko'),
('KY', 'CYM', 'Kajmanské ostrovy'),
('KH', 'KHM', 'Kambodža'),
('CM', 'CMR', 'Kamerun'),
('CA', 'CAN', 'Kanada'),
('CV', 'CPV', 'Kapverdy'),
('QA', 'QAT', 'Katar'),
('KZ', 'KAZ', 'Kazachstán'),
('KE', 'KEN', 'Keòa'),
('KI', 'KIR', 'Kiribati'),
('CC', 'CCK', 'Kokosové ostrovy'),
('CO', 'COL', 'Kolumbie'),
('KM', 'COM', 'Komory'),
('CG', 'COG', 'Kongo'),
('CD', 'COD', 'Konžská demokratická republika'),
('CR', 'CRI', 'Kostarika'),
('CU', 'CUB', 'Kuba'),
('KW', 'KWT', 'Kuvajt'),
('CY', 'CYP', 'Kypr'),
('KG', 'KGZ', 'Kyrgyzstán'),
('LA', 'LAO', 'Laos'),
('LS', 'LSO', 'Lesotho'),
('LB', 'LBN', 'Libanon'),
('LR', 'LBR', 'Libérie'),
('LY', 'LBY', 'Libye'),
('LI', 'LIE', 'Lichtenštejnsko'),
('LT', 'LTU', 'Litva'),
('LV', 'LVA', 'Lotyšsko'),
('LU', 'LUX', 'Lucembursko'),
('MO', 'MAC', 'Macao'),
('MG', 'MDG', 'Madagaskar'),
('HU', 'HUN', 'Maïarsko'),
('MY', 'MYS', 'Malajsie'),
('MW', 'MWI', 'Malawi'),
('MV', 'MDV', 'Maledivy'),
('ML', 'MLI', 'Mali'),
('MT', 'MLT', 'Malta'),
('IM', 'IMN', 'Ostrov Man'),
('MA', 'MAR', 'Maroko'),
('MH', 'MHL', 'Marshallovy ostrovy'),
('MQ', 'MTQ', 'Martinik'),
('MU', 'MUS', 'Mauricius'),
('MR', 'MRT', 'Mauritánie'),
('YT', 'MYT', 'Mayotte'),
('UM', 'UMI', 'Menší odlehlé ostrovy USA'),
('MX', 'MEX', 'Mexiko'),
('FM', 'FSM', 'Mikronésie'),
('MD', 'MDA', 'Moldavsko'),
('MC', 'MCO', 'Monako'),
('MN', 'MNG', 'Mongolsko'),
('MS', 'MSR', 'Montserrat'),
('MZ', 'MOZ', 'Mosambik'),
('MM', 'MMR', 'Myanmar'),
('NA', 'NAM', 'Namibie'),
('NR', 'NRU', 'Nauru'),
('DE', 'DEU', 'Nìmecko'),
('NP', 'NPL', 'Nepál'),
('NE', 'NER', 'Niger'),
('NG', 'NGA', 'Nigérie'),
('NI', 'NIC', 'Nikaragua'),
('NU', 'NIU', 'Niue'),
('NL', 'NLD', 'Nizozemsko'),
('NF', 'NFK', 'Norfolk'),
('NO', 'NOR', 'Norsko'),
('NC', 'NCL', 'Nová Kaledonie'),
('NZ', 'NZL', 'Nový Zéland'),
('OM', 'OMN', 'Omán'),
('PK', 'PAK', 'Pákistán'),
('PW', 'PLW', 'Palau'),
('PS', 'PSE', 'Palestinská autonomie'),
('PA', 'PAN', 'Panama'),
('PG', 'PNG', 'Papua Nová Guinea'),
('PY', 'PRY', 'Paraguay'),
('PE', 'PER', 'Peru'),
('PN', 'PCN', 'Pitcairnovy ostrovy'),
('CI', 'CIV', 'Pobøeží slonoviny'),
('PL', 'POL', 'Polsko'),
('PR', 'PRI', 'Portoriko'),
('PT', 'PRT', 'Portugalsko'),
('AT', 'AUT', 'Rakousko'),
('RE', 'REU', 'Réunion'),
('GQ', 'GNQ', 'Rovníková Guinea'),
('RO', 'ROU', 'Rumunsko'),
('RU', 'RUS', 'Rusko'),
('RW', 'RWA', 'Rwanda'),
('GR', 'GRC', 'Øecko'),
('PM', 'SPM', 'Saint Pierre a Miquelon'),
('SV', 'SLV', 'Salvador'),
('WS', 'WSM', 'Samoa'),
('SM', 'SMR', 'San Marino'),
('SA', 'SAU', 'Saúdská Arábie'),
('SN', 'SEN', 'Senegal'),
('KP', 'PRK', 'Severní Korea'),
('MK', 'MKD', 'Severní Makedonie'),
('MP', 'MNP', 'Severní Mariany'),
('SC', 'SYC', 'Seychely'),
('SL', 'SLE', 'Sierra Leone'),
('SG', 'SGP', 'Singapur'),
('SK', 'SVK', 'Slovensko'),
('SI', 'SVN', 'Slovinsko'),
('SO', 'SOM', 'Somálsko'),
('AE', 'ARE', 'Spojené arabské emiráty'),
('GB', 'GBR', 'Spojené království Velké Británie a Severního Irska'),
('US', 'USA', 'Spojené státy americké'),
('RS', 'SRB', 'Srbsko'),
('LK', 'LKA', 'Srí Lanka'),
('CF', 'CAF', 'Støedoafrická republika'),
('SD', 'SDN', 'Súdán'),
('SR', 'SUR', 'Surinam'),
('SH', 'SHN', 'Svatá Helena, Ascension a Tristan da Cunha'),
('LC', 'LCA', 'Svatá Lucie'),
('BL', 'BLM', 'Svatý Bartolomìj'),
('KN', 'KNA', 'Svatý Kryštof a Nevis'),
('MF', 'MAF', 'Svatý Martin (francouzská èást)'),
('SX', 'SXM', 'Svatý Martin (nizozemská èást)'),
('ST', 'STP', 'Svatý Tomáš a Princùv ostrov'),
('VC', 'VCT', 'Svatý Vincenc a Grenadiny'),
('SZ', 'SWZ', 'Svazijsko'),
('SY', 'SYR', 'Sýrie'),
('SB', 'SLB', 'Šalomounovy ostrovy'),
('ES', 'ESP', 'Španìlsko'),
('SJ', 'SJM', 'Špicberky a Jan Mayen'),
('SE', 'SWE', 'Švédsko'),
('CH', 'CHE', 'Švýcarsko'),
('TJ', 'TJK', 'Tádžikistán'),
('TZ', 'TZA', 'Tanzanie'),
('TH', 'THA', 'Thajsko'),
('TW', 'TWN', 'Tchaj-wan'),
('TG', 'TGO', 'Togo'),
('TK', 'TKL', 'Tokelau'),
('TO', 'TON', 'Tonga'),
('TT', 'TTO', 'Trinidad a Tobago'),
('TN', 'TUN', 'Tunisko'),
('TR', 'TUR', 'Turecko'),
('TM', 'TKM', 'Turkmenistán'),
('TC', 'TCA', 'Turks a Caicos'),
('TV', 'TUV', 'Tuvalu'),
('UG', 'UGA', 'Uganda'),
('UA', 'UKR', 'Ukrajina'),
('UY', 'URY', 'Uruguay'),
('UZ', 'UZB', 'Uzbekistán'),
('CX', 'CXR', 'Vánoèní ostrov'),
('VU', 'VUT', 'Vanuatu'),
('VA', 'VAT', 'Vatikán'),
('VE', 'VEN', 'Venezuela'),
('VN', 'VNM', 'Vietnam'),
('TL', 'TLS', 'Východní Timor'),
('WF', 'WLF', 'Wallis a Futuna'),
('ZM', 'ZMB', 'Zambie'),
('EH', 'ESH', 'Západní Sahara'),
('ZW', 'ZWE', 'Zimbabwe')